// Copyright 2025 Undistro Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build oracle

package oracle

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	yamlv2 "go.yaml.in/yaml/v2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/applyconfigurations"
	"k8s.io/client-go/kubernetes/scheme"
	smdschema "sigs.k8s.io/structured-merge-diff/v6/schema"
	"sigs.k8s.io/structured-merge-diff/v6/typed"
)

var updateBuiltins = flag.Bool("update-builtins", false,
	"rewrite k8s/builtinschema.yaml and k8s/builtingvks.yaml from the client-go this module is built against")

// The two files the wasm binary embeds to give ApplyConfiguration mutations
// server-side-apply merge semantics.
const (
	builtinSchemaFile = "../builtinschema.yaml"
	builtinGVKsFile   = "../builtingvks.yaml"
)

const generatedHeader = `# Copyright 2026 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by k8s/oracle: go test -tags oracle -run TestBuiltinSchemaIsCurrent -update-builtins
# Do not edit. %s
`

// TestBuiltinSchemaIsCurrent holds the wasm binary's copy of the built-in
// merge schema to account against the client-go it is compiled beside.
//
// The playground needs a structured-merge-diff schema to merge an
// ApplyConfiguration the way a cluster does -- keyed lists by key rather than
// wholesale. A cluster reads one per group-version from its own /openapi/v3;
// upstream's patch.NewTypeConverterManager does exactly that, over an HTTP
// client, which a browser has nowhere to point. The only in-process producer of
// the same schema is client-go's generated apply-configuration parser, and
// reaching it means importing k8s.io/client-go/kubernetes/scheme and
// k8s.io/client-go/applyconfigurations -- measured at +3.35 MB gzip, 14x the
// cost of the whole rest of the mode.
//
// So the schema travels as data instead of as code: this test extracts it here,
// where importing client-go is free, and the binary embeds the result. That
// makes it a generated artifact, and a generated artifact that nothing checks
// rots silently, which is what this test is. On a client-go bump it fails and
// names the command that fixes it.
func TestBuiltinSchemaIsCurrent(t *testing.T) {
	wantSchema, wantGVKs, err := generateBuiltins()
	if err != nil {
		t.Fatalf("generating the built-in schema: %v", err)
	}
	for _, file := range []struct {
		path    string
		content []byte
	}{{builtinSchemaFile, wantSchema}, {builtinGVKsFile, wantGVKs}} {
		if *updateBuiltins {
			if err := os.WriteFile(file.path, file.content, 0o644); err != nil {
				t.Fatalf("writing %s: %v", file.path, err)
			}
			t.Logf("wrote %s (%d bytes)", file.path, len(file.content))
			continue
		}
		got, err := os.ReadFile(file.path)
		if err != nil {
			t.Fatalf("reading %s: %v", file.path, err)
		}
		if string(got) != string(file.content) {
			t.Errorf("%s is %d bytes and client-go now generates %d; rerun\n"+
				"    cd k8s/oracle && go test -tags oracle -run TestBuiltinSchemaIsCurrent -update-builtins",
				filepath.Base(file.path), len(got), len(file.content))
		}
	}
}

// generateBuiltins returns the merge schema and the group-version-kind index
// the binary embeds.
//
// client-go publishes its schema only from behind a TypeConverter, so it is
// read back off a parsed value; any registered kind will do and ConfigMap is
// the cheapest. Marshalling the result with the same YAML library
// typed.NewParser reads is a byte-exact round trip of the literal client-go
// carries, which is what makes the embedded copy a copy rather than a
// translation.
func generateBuiltins() (schemaYAML, gvksYAML []byte, err error) {
	probe, err := applyconfigurations.NewTypeConverter(scheme.Scheme).ObjectToTyped(
		&corev1.ConfigMap{TypeMeta: metav1.TypeMeta{APIVersion: "v1", Kind: "ConfigMap"}})
	if err != nil {
		return nil, nil, fmt.Errorf("reading client-go's generated schema: %w", err)
	}
	generated := probe.Schema()

	body, err := yamlv2.Marshal(&smdschema.Schema{Types: generated.Types})
	if err != nil {
		return nil, nil, fmt.Errorf("marshalling the schema: %w", err)
	}
	parser := &typed.Parser{Schema: smdschema.Schema{Types: generated.Types}}

	// Only the kinds the schema actually has a type for. A definition name the
	// parser does not know would make every merge of that kind fail rather than
	// fall back to the deduced converter.
	var gvks []schema.GroupVersionKind
	for gvk := range scheme.Scheme.AllKnownTypes() {
		gvks = append(gvks, gvk)
	}
	sort.Slice(gvks, func(i, j int) bool { return gvks[i].String() < gvks[j].String() })
	index := yamlv2.MapSlice{}
	for _, gvk := range gvks {
		name, err := scheme.Scheme.ToOpenAPIDefinitionName(gvk)
		if err != nil || !parser.Type(name).IsValid() {
			continue
		}
		index = append(index, yamlv2.MapItem{Key: gvk.GroupVersion().String() + "/" + gvk.Kind, Value: name})
	}
	indexBody, err := yamlv2.Marshal(index)
	if err != nil {
		return nil, nil, fmt.Errorf("marshalling the group-version-kind index: %w", err)
	}

	header := func(provenance string) string {
		return fmt.Sprintf(generatedHeader, provenance)
	}
	schemaYAML = []byte(header("This is client-go's generated apply-configuration merge schema, verbatim.") + strings.TrimRight(string(body), "\n") + "\n")
	gvksYAML = []byte(header("Each kind client-go's scheme knows, mapped to its name in builtinschema.yaml.") + strings.TrimRight(string(indexBody), "\n") + "\n")
	return schemaYAML, gvksYAML, nil
}
